app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');
Route::resource('/','WelcomeController');
Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');


// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){
Route::resource('users','UsersController');
Route::resource('admin','AdminController');
Route::resource('admin.staffs','StaffsController');
Route::resource('admin.plots','PlotsController');
Route::resource('plots','PlotsController');
Route::resource('agents','AgentsController');
Route::resource('staffs','StaffsController');
Route::resource('payments','PaymentsController');
Route::resource('cocuments', 'DocumentsController');
Route::resource('customers', 'CustomersController');
Route::resource('search', 'SearchController');
Route::resource('partners', 'PartnersController');
Route::resource('transactions', 'TransactionsController');
Route::resource('prospectives', 'ProspectivesController');
Route::resource('tenants', 'TenantsController');
Route::resource('tenants.payments', 'TenanPaymentsController');
Route::resource('land-lords', 'LandlordsController');
Route::resource('compounds', 'CompoundsController');
Route::resource('houses', 'HousesController');
Route::resource('notifications', 'NotificationsController');
Route::get('data-entry', array('as'=>'data_entry', 'uses'=>'PagesController@showData'));
Route::resource('estates', 'EstatesController');
Route::resource('estates.plots', 'EstatesController');
});
#THIS IS THE TESTING PART BELOW
// Event::listen('illuminate.query',function($query){
// echo '<pre style="margin:200px 80px">';
// print_r($query);
// echo '</pre>';
// });

app/models/Tenant.php
<?php

class Tenant extends \Eloquent {
	protected $fillable = [
'tent_id',
'tent_houseID',
'tent_compoundID',
'tent_rentID',
'tent_personid',
'tent_advance',
'tent_monthlyFee',
'tent_paymentStype',
'tent_status'
];

	public function house(){
		return $this->belongsTo('House','tent_houseID','hous_id');
	}
	public function person(){
		return $this->belongsTo('Person','tent_personid','id');
	}
	public function rents(){
		return $this->hasMany('Rent','rent_tenantID','tent_id');
	}
}

app/controllers/TenantsController.php
<?php

class TenantsController extends \AdminController {

	/**
	 * Display a listing of the resource.
	 * GET /tenants
	 *
	 * @return Response
	 */
	public function index()
	{
		// $all = House::with('tenants')->get();
		$all = Tenant::with('house','person.contacts')->get();
		$all = ($all)? $all->toArray() : [];
		$this->layout->content = View::make('admin.Tenants.index')->with('tenants',$all);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /tenants/create
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('admin.Tenants.create');
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /tenants
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$person = array();
		$staff = array();
		$address = array();
		$contact = array();
		$done = false;
		if ($input) :
			foreach ($input as $k => $table) {
				if (is_array($table)) {
					if ($k == 'person') {
						$V = new services\validators\Person($table);
						if($V->passes()){
							$person = Person::create(array(
							'pers_fname' => $table['fname'], 
							'pers_mname' => ($table['mname']) ?: null, 
							'pers_lname' => $table['lname'], 
							'pers_type' => 'Tenant', 
							'pers_DOB' => $table['dob'], 
							'pers_gender' => $table['Pers_Gender'], 
							'pers_nationality' => $table['Pers_Nationality'], 
							'pers_ethnicity' => $table['Pers_Ethnicity'], 
							));
							if ($person->id) {
								$done = true;
							}
						}else{
							$errors = $V->errors;
							return Redirect::back()->withErrors($errors)->withInput();							
						}


					}
					if ($k == 'address') {
						$address = $table;
						if ($person->id) {
							$address = array_add($address, 'Addr_EntityID', $person->id);
							$address = array_add($address, 'Addr_EntityType', 'Person');
							$V = new services\validators\Address($table);
							if($V->passes()){
								$address = Address::create($address);
							}
						}
						$errors = $V->errors;

					}
					if ($k == 'contact') {

						

						if ($person->id) {

							$V = new services\validators\Contact($table);
							foreach ($table as $key => $value) {
								if($V->passes()){

									if(!empty($value)){
										$contact = Contact::create(array(
										'Cont_EntityID' => $person->id,	
										'Cont_EntityType' => 'Person',	
										'Cont_Contact' => $value,	
										'Cont_ContactType' =>  $key	
										));

									$contact = $contact->toArray();
									}
								}
							}
							$errors = $V->errors;
						}
					}
				if ($k == 'cust') {
					#loop hole here not comming in values controlls
					// dd($input);
					// Tenant::create(array(
					// 		'tent_houseID'=> $input[''],
					// 		'tent_compoundID'=> $input[''],
					// 		'tent_rentID'=> $input[''],
					// 		'tent_advance'=> $input[''],
					// 		'tent_monthlyFee'=> $input[''],
					// 		'tent_paymentStype'=> $input[''],
					// 		'tent_status'=> $input['']
					// ));

					}

				}
			}
			if($done){

			$house = House::where('hous_id','=',$input['houseID'])->first();
			$house = $house ?: $house->toArray();
			$tent = Tenant::create(array(
					'tent_houseID'=> $input['houseID'],
					'tent_compoundID'=> $house['hous_compoundID'],
					'tent_advance'=> $input['down_payment'],
					'tent_personid'=> $person->id
			));
			// we add rent 
			$montlyfee = $input['Monthly_fee'] ?:  $house['hous_price'] ;
			Rent::create(array(
				'rent_houseID' => $input['houseID'],
				'rent_tenantID' => $tent->id,
				'rent_advance' => $input['down_payment'],
				'rent_firstmonthpaid' => null,
				'rent_nextpaydate' => null,
				'rent_monthlyFee' => $montlyfee
			));

				Flash::message("Successfully added a Tenant");
				return Redirect::back();
			}else{
				return Redirect::back()->withErrors($errors)->withInput();							
			}
		endif;
	}

	/**
	 * Display the specified resource.
	 * GET /tenants/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		// $all = Rent::with('payments')->first();
		$all = Tenant::with('house.compound','person.contacts','person.addresses','rents.payments')->whereRaw('tent_id = ? AND deleted = ? AND tent_status = ?',[$id,0,0])->first();
		$all = ($all)? $all->toArray() : [];
		$this->layout->content = View::make('admin.Tenants.show')->with('tenant',$all);
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /tenants/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /tenants/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /tenants/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/views/admin/Tenants/create.blade.php
<?php #page specific processing
// $plots = Plot::all()->toArray(); 
 ?>
@include('templates/top-admin')
@section('content')
	<div class="cc">
		<div class="create-department">
			<div class="form-snippet">
				<div class="form-header">
					<div class="title">
						<h2>Add A New Tenant </h2>
					</div>

				</div>
				<div class="messages">
					@include('flash::message')
					@include('__partials/errors')
				</div>
				{{Form::open(['route'=>'tenants.store'],[],['class'=>'form-snippet'])}}

					<div class="level details">

						<div class="first">
							<div>
								{{Form::label('person[fname]','First Name')}}
								{{Form::text('person[fname]',null,['class'=>'input-xlarge','placeholder'=>'Enter first name','required'=>1])}}
							</div>
							<div>
								{{Form::label('person[mname]','Middle Name')}}
								{{Form::text('person[mname]',null,['class'=>'input-xlarge','placeholder'=>'Enter middle name'])}}
							</div>
							<div>
								{{Form::label('person[lname]','Last Name')}}
								{{Form::text('person[lname]',null,['class'=>'input-xlarge','placeholder'=>'Enter last name','required'=>1])}}
							</div>							
						</div>
					</div>
					<div class="level details">
						<span>Bio </span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('person[dob]','Birthday')}}
								{{Form::date('person[dob]',['class'=>'input-xlarge','placeholder'=>'Enter admission date','required'=>1])}}
							</div>
							<div>
								{{Form::label('person[Pers_Ethnicity]','Ethniticity')}}
								<select name="person[Pers_Ethnicity]" id="enit" class="input-xlarge">
									<?php $countries = Variable::domain('Pers_Ethnicity')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select>
							</div>
							<div>
								{{Form::label('person[Pers_Nationality]','Nationality')}}
								<select name="person[Pers_Nationality]" id="nation" class="input-xlarge">
									<?php $countries = Variable::domain('Country')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select>
							</div>
							<div>
								{{Form::label('person[Pers_Gender]','Gender')}}
								{{Form::select('person[Pers_Gender]', array('male' => 'Male','female' => 'Female'));}}
							</div>
						</div>
					</div>
					<div class="level details">
						<span>Address</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('address[Addr_Town]','Town')}}
								{{Form::text('address[Addr_Town]',null,['class'=>'input-xlarge','placeholder'=>'Enter town'])}}
							</div>
							<div>
								{{Form::label('address[Addr_District]','District')}}
								<select name="address[Addr_District]" id="region">
									<?php $countries = Variable::domain('Addr_District')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select> 
							</div>
							<div>
								{{Form::label('address[Addr_AddressStreet]','street')}}
								{{Form::text('address[Addr_AddressStreet]',null,['class'=>'input-xlarge','placeholder'=>'Enter street'])}}
							</div>
						</div>
					</div>
					<div class="level details">
						<span>Contact</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('contact[phones]','Phones')}}
								{{Form::text('contact[phones]',null,['class'=>'input-xlarge','placeholder'=>'Enter phone number(S)'])}}
							</div>
							<div>
								{{Form::label('contact[email]','Email')}}
								{{Form::text('contact[email]',null,['class'=>'input-xlarge','placeholder'=>'Enter Email address'])}} 
							</div>
							<div>
								{{Form::label('contact[telephone]',' Telephone (land line)')}}
								{{Form::text('contact[telephone]',null,['class'=>'input-xlarge','placeholder'=>'Enter numbers'])}}
							</div>
						</div>
					</div>
					<div class="level details">
						<span>House details</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('house','House number')}}
								<select name="houseID">
								<?php
									 $houses = House::all();
									 $house = ($houses)? $houses->toArray() : [];
								?>
								<?php if (!empty($house)): ?>
									<?php foreach ($house as $key => $value): ?>
										<option value="{{$value['hous_id']}}">{{$value['hous_number']}}</option>
									<?php endforeach ?>
									<?php else: ?>
									<option value="0">Not Available</option>
								<?php endif ?>
								</select>
								
							</div>
							<div>
								{{Form::label('Monthly_fee','Monthly Fee')}}
					{{Form::number('Monthly_fee',['class'=>'input-xlarge','placeholder'=>'Enter monthly fee only when needed','step'=>'any'])}} 

							</div>
							<div>
{{Form::label('down_payment','Down payment')}}
{{Form::number('down_payment',['class'=>'input-xlarge','placeholder'=>'Enter down payment in dalasis','required'=>1,'step'=>'any'])}} 
							</div>
						</div>
					</div>
					<div class="level actions">
						<div>
							  <button type="submit" class="btn btn-large btn-primary span6" name="save" value="save">Add Tenant</button>
						</div>
					</div>
				{{Form::close()}}
			</div>
		</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/Tenants/edit.blade.php
C:\wamp\www\universal\app/views/Tenants/edit.blade.php

app/views/admin/Tenants/index.blade.php
@include('templates/top-admin')
@section('content')
	<div class="c-header cc">
		<h3>Tenants <a href="#myModal" role="button" data-toggle="modal"><i class="fa fa-plus"></i></a></h3>
	</div>
	<div class="cc">
				<table class="table">
					<thead>
						<tr>
							<th>Fullname</th>
							<th>Nationality</th>
							<th>Gender</th>
							<th>House number</th>
							<th>House price</th>
							<th>created</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						<?php if (!empty($tenants)): ?>
							<?php foreach ($tenants as $key => $value): ?>
							<tr>
								<td>
									<a href="{{route('tenants.show',$value['tent_id'])}}">
									{{ucwords(e($value['person']['pers_fname'].' '.$value['person']['pers_mname'].' '.$value['person']['pers_lname']))}}
									</a>								
								</td>
								<td>
									{{ucwords(e($value['person']['pers_nationality']))}}
								</td>
								<td>
									{{ucwords(e($value['person']['pers_gender']))}}
								</td>
								<td>
									{{ucwords(e($value['house']['hous_number']))}}
								</td>
								<td>
									{{ucwords(e($value['house']['hous_price']))}}
								</td>
								<td>
									{{ucwords(e($value['created_at']))}}
								</td>
								<td>
									<a href="{{route('tenants.show',$value['tent_id'])}}">view</a> | 
									<a href="#"> options</a>
								</td>
							</tr>						
							<?php endforeach ?>
							<?php else: ?>
							<tr>
								<td colspan="8"><h4>No Tenance Available!</h4></td>
							</tr>
						<?php endif ?>
					</tbody>
				</table>

		  </div>
		</div>
	</div>
@stop
@include('templates/bottom-admin')