app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');
Route::resource('/','WelcomeController');
Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');


// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){
Route::resource('users','UsersController');
Route::resource('admin','AdminController');
Route::resource('admin.staffs','StaffsController');
Route::resource('admin.plots','PlotsController');
Route::resource('plots','PlotsController');
Route::resource('agents','AgentsController');
Route::resource('staffs','StaffsController');
Route::resource('payments','PaymentsController');
Route::resource('cocuments', 'DocumentsController');
Route::resource('customers', 'CustomersController');
Route::resource('search', 'SearchController');
Route::resource('partners', 'PartnersController');
Route::resource('transactions', 'TransactionsController');
Route::resource('prospectives', 'ProspectivesController');
Route::resource('tenants', 'TenantsController');
Route::resource('tenants.payments', 'TenanPaymentsController');
Route::resource('land-lords', 'LandlordsController');
Route::resource('compounds', 'CompoundsController');
Route::resource('houses', 'HousesController');
Route::resource('notifications', 'NotificationsController');
Route::get('data-entry', array('as'=>'data_entry', 'uses'=>'PagesController@showData'));
Route::resource('estates', 'EstatesController');
Route::resource('estates.plots', 'EstatesController');
});
#THIS IS THE TESTING PART BELOW
// Event::listen('illuminate.query',function($query){
// echo '<pre style="margin:200px 80px">';
// print_r($query);
// echo '</pre>';
// });

app/controllers/TransactionsController.php
<?php

class TransactionsController extends \AdminController {

	/**
	 * Display a listing of the resource.
	 * GET /transactions
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('admin.transactions.index');
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /transactions/create
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /transactions
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}

	/**
	 * Display the specified resource.
	 * GET /transactions/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /transactions/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /transactions/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /transactions/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/views/admin/transactions/create.blade.php
C:\wamp\www\universal\app/views/Transactions/create.blade.php

app/views/admin/transactions/edit.blade.php
C:\wamp\www\universal\app/views/Transactions/edit.blade.php

app/views/admin/transactions/index.blade.php
@include('templates/top-admin')
@section('content')
@include('__partials/modal-add-trans')
	<div class="c-header cc">
		<h3>Daily transactions <a href="#myModal" role="button" data-toggle="modal">	<i class="fa fa-plus"></i></a></h3>

	</div>
	<div class="cc">

				<table class="table">
					<thead>
						<tr>
							<th>#</th>
							<th>Details</th>
							<th>Date</th>
							<th>By</th>
							<th>Amount</th>
							<th>Remarks</th>
							<th>created</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						<?php if (!empty($Partners)): ?>
							<?php foreach ($Partners as $key => $value): ?>
							<tr>
								<td>{{$key+1}}</td>
								<td>{{ucwords($value['name'])}}</td>
								<td><a href="{{route('departments.show',$value['depart_id'])}}">{{ucwords($value['department']['name'])}}</a></td>
								<td><a href="{{route('departments.staffs.show',[$value['depart_id'],$value['staffID']])}}">{{ucwords($value['staff']['Staff_HighestQualification'])}}</a></td>
								<td><?php echo ($value['fee']) ?: 'N/A' ;?></td>
								<td><?php echo ($value['duration']) ?: 'N/A' ;?></td>
								<td><?php echo ($value['qualification']) ?: 'not specified' ;?></td>
								<td><a href="{{route('departments.Partners.show',[$value['depart_id'],$value['id']])}}">View Course</a></td>
							</tr>						
							<?php endforeach ?>
							<?php else: ?>
							<tr>
								<td colspan="8"><h4>No Customers Available!</h4></td>
							</tr>
						<?php endif ?>
					</tbody>
				</table>

		  </div>
		</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/transactions/show.blade.php
@include('templates/top-admin')
@section('content')
	<div class="c-header cc">
		<h3>Plots</h3>
	</div>
	<div class="cc">
		<table class="table">
			<thead>
				<tr>
					<th>#</th>
					<th>Plot Name</th>
					<th>Plot Size</th>
					<th>Plot Price</th>
					<th>Plot Created</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<?php if (!empty($Plots)): ?>
				<?php $depart = $Plots->get()->toArray(); ?>
					<?php foreach ( $depart as $key => $value ): ?>
						<tr>
							<td>{{$key + 1}}</td>
							<td>{{e($value['name'])}}</td>
							<td>{{e($value['personName'])}}</td>
							<td>
								<?php if (!empty($value['courses'])): ?>
									<ul class="courseLi">
										<?php foreach ($value['courses'] as $key2 => $value2): ?>
											<li><a href="{{route('Plots.courses.show',[$value['id'],$value2['id']])}}">{{$value2['name']}}</a></li>	
										<?php endforeach ?>
									</ul>									
								<?php endif ?>
							</td>
							<td>{{e($value['created_at'])}}</td>
							<td>{{e($value['updated_at'])}}</td>
						</tr>
					<?php endforeach ?>
					<?php else: ?>
					<tr>
						<td colspan="6"><h4>No Plot!</h4></td>
					</tr>
				<?php endif ?>
			</tbody>
		</table>
	</div>
@stop
@include('templates/bottom-admin')