app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');
Route::resource('/','WelcomeController');
Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');


// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){
Route::resource('users','UsersController');
Route::resource('admin','AdminController');
Route::resource('admin.staffs','StaffsController');
Route::resource('admin.plots','PlotsController');
Route::resource('plots','PlotsController');
Route::resource('agents','AgentsController');
Route::resource('staffs','StaffsController');
Route::resource('payments','PaymentsController');
Route::resource('cocuments', 'DocumentsController');
Route::resource('customers', 'CustomersController');
Route::resource('search', 'SearchController');
Route::resource('partners', 'PartnersController');
Route::resource('transactions', 'TransactionsController');
Route::resource('prospectives', 'ProspectivesController');
Route::resource('tenants', 'TenantsController');
Route::resource('tenants.payments', 'TenanPaymentsController');
Route::resource('land-lords', 'LandlordsController');
Route::resource('compounds', 'CompoundsController');
Route::resource('houses', 'HousesController');
Route::resource('notifications', 'NotificationsController');
Route::get('data-entry', array('as'=>'data_entry', 'uses'=>'PagesController@showData'));
Route::resource('estates', 'EstatesController');
Route::resource('estates.plots', 'EstatesController');
});
#THIS IS THE TESTING PART BELOW
// Event::listen('illuminate.query',function($query){
// echo '<pre style="margin:200px 80px">';
// print_r($query);
// echo '</pre>';
// });

app/models/Compound.php
<?php

class Compound extends \Eloquent {
	protected $fillable = [
	'comp_id',
	'comp_landLordID',
	'comp_numberOfHouses',
	'comp_size',
	'comp_remarks',
	'location',
	'comp_indentifier'
	];


	public function scopeAvailable($query){
		return $query->whereRaw('deleted != ? AND comp_landLordID = ?',[0,0])->get();
	}

	public function landlord(){
		return $this->belongsto('Landlord','comp_landLordID','id');
	}
	public function houses(){
		return $this->hasMany('House','hous_compoundID','comp_id');
	}
}

app/controllers/CompoundsController.php
<?php
	/** Topics
		1. Notices
			- no validation 
	 * 			#notice 01
	 *  
	 *
	 * @return Response {}
	 */
class CompoundsController extends \AdminController {

	/**
	 * Display a listing of the resource.
	 * GET /compounds
	 *
	 * @return Response
	 */
	public function index()
	{
		$all = Compound::with('landlord')->get();
		$all = ($all) ? $all->toArray() : [];
		$this->layout->content = View::make('admin.Compounds.index')->with('compounds',$all);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /compounds/create
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('admin.Compounds.create');
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /compounds
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();

		if(Request::ajax()):
			$data = array();
			$fname = '';
			$mname = '';
			$lname = '';
			$keywords = [];
			if (str_contains($input['fullname'], ' ')) {
				
				$keywords = preg_split("/[\s]+/", trim($input['fullname']));
				// $t = count($keywords);
				// if ( $t > 2) {
				// 	for($i = 0; $i >= $t; $i++){
				// 		if ($i != 0 && $i != $t) {
				// 			$mname .= $keywords[$i].' ';
				// 		}else{
				// 			if($i != 0){
				// 				$fname .= $keywords[$i];	
				// 			}else{
				// 				$lname .= $keywords[$i];	
				// 			}
				// 		}
				// 	}
				// }
			}
			$person = Person::create(array(
					'pers_fname'=> (head($keywords)) ?: '',
					'pers_mname'=> ($keywords[1]) ?: '',
					'pers_lname'=> (last($keywords)) ?: '',
					'pers_type'=> 'Landlord'
			));
			$ll = Landlord::create(array('ll_fullname' =>$input['fullname'],'ll_personid'=>$person->id));
			$data['compound'] = Compound::create(array(
				'comp_landLordID' => $ll->id,
				'comp_numberOfHouses' => e($input['Compound_houses']),
				'location' => e($input['Compound_location'])
			));

			$data['contact'] = Contact::create(array(
				'Cont_EntityID' => $person->id,	
				'Cont_EntityType' => 'Person',	
				'Cont_Contact' => e($input['contacts']),	
				'Cont_ContactType' =>  'Phone'
			));

			$data['address'] = Address::create(array(
				 'Addr_EntityID' => $person->id,	
				 'Addr_EntityType' => 'Person', 
				 'Addr_AddressStreet' => e($input['address']),				
			));
			$data['landlord'] = $ll;
			return Response::json( $data );

		endif;

		#notice 0.1
		// add compound v0.0.1 #no validation
		$compound =  Compound::create(array(
			'comp_numberOfHouses'=> $input['comp_houses'],
			'comp_size'=> $input['comp_size'],
			'comp_remarks'=> $input['comp_remarks'],
			'location'=> $input['comp_location'],
			'comp_indentifier'=> $input['comp_number']		
		));
		if( $compound ){
				Flash::message("Successfully added a Compound");
				return Redirect::back();
			}else{
				return Redirect::back()->withErrors($errors)->withInput();							
			}
	}

	/**
	 * Display the specified resource.
	 * GET /compounds/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /compounds/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /compounds/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /compounds/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/views/admin/Compounds/create.blade.php
@include('templates/top-admin')
@section('content')
	<div class="cc">
		<div class="create-comp">
			<div class="form-snippet">
				<div class="form-header">
					<div class="title">
						<h2>Add a new compound </h2>
					</div>
				</div>
				<div class="messages">
					@include('flash::message')
					@include('__partials/errors')
				</div>
				{{Form::open(['route'=>'compounds.store'],[],['class'=>'form-snippet'])}}
					<div class="level name">

						<div>
							{{Form::label('comp_size','Compound Size')}}
							{{Form::text('comp_size',null,['class'=>'input-xlarge span6','placeholder'=>'Compound Size'])}}
						</div>
						<div>
							{{Form::label('comp_houses','Number of houses')}}
							{{Form::number('comp_houses',['class'=>'input-xlarge span6','placeholder'=>'Compound number of houses','step'=>'any'])}}
						</div>
					</div>
					<div class="level name">
						<div>
							{{Form::label('comp_location','Compound location')}}
							{{Form::text('comp_location',null,['class'=>'input-xlarge span6','placeholder'=>'Compound location or Adress'])}}
						</div>
						<div>
							{{Form::label('comp_number','Compound number')}}
							{{Form::text('comp_number',null,['class'=>'input-xlarge span6','placeholder'=>'Compound number or Indentifier'])}}
						</div>
					</div>
					<div class="level">
						<div>
							{{Form::label('comp_remarks','Compound Remarks')}}
							{{Form::textarea('comp_remarks',null,['class'=>'input-xlarge span12','placeholder'=>'Enter your remarks here'])}}
						</div>
					</div>
					<div class="level actions">
						<div>
							  <button type="submit" class="btn btn-large btn-primary span12" name="save" value="save">Create Compound</button>
						</div>
					</div>
				{{Form::close()}}
			</div>
		</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/Compounds/edit.blade.php
C:\wamp\www\universal\app/views/Compounds/edit.blade.php

app/views/admin/Compounds/index.blade.php
@include('templates/top-admin')
@section('content')
@include('__partials/modal-add-compound')
	<div class="c-header cc">
		<h3>Compounds <a href="#myModal" role="button" data-toggle="modal">	<i class="fa fa-plus"></i></a></h3>
	</div>
	<div class="cc">
				<div class="messages">
					@include('flash::message')
					@include('__partials/errors')
				</div>
				<table class="table">
					<thead>
						<tr>
							<th>Owner</th>
							<th>Houses</th>
							<th>Remarks</th>
							<th>created</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						<?php if (!empty($compounds)): ?>
							<?php foreach ($compounds as $key => $value): ?>
							<tr>
								<td>
									<?php if ($value['landlord']): ?>
										<a href="{{route('land-lords.show',$value['landlord']['id'])}}">{{ucwords(e($value['landlord']['ll_fullname']))}}</a>
										<?php else: ?>
										No owner
									<?php endif ?>
								</td>
								<td>	
									{{$value['comp_numberOfHouses']}}
								</td>
								<td>	
									{{$value['comp_remarks']}}
								</td>
								<td>	
									{{$value['created_at']}}
								</td>
								<td>	
									<a href="{{route('compounds.show',$value['comp_id'])}}">view</a> |
									<a href="#">Options</a>
								</td>
							</tr>						
							<?php endforeach ?>
							<?php else: ?>
							<tr>
								<td colspan="8"><h4>No Compounds Available!</h4></td>
							</tr>
						<?php endif ?>
					</tbody>
				</table>

		  </div>
		</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/Compounds/show.blade.php
C:\wamp\www\universal\app/views/Compounds/show.blade.php